[package]
name = "inline_hook"
version = "0.1.0"
authors = ["StackDoubleFlow <ojaslandge@gmail.com>"]
edition = "2021"

[dependencies]
cfg-if = "1"

[target.'cfg(not(target_os = "android"))'.dependencies]
retour = "0.3"

[build-dependencies]
cc = "1"
