name: Docs
on:
  push:
    branches:
      - master

jobs:
  docs:
    name: Docs
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          target: aarch64-linux-android
          profile: minimal
          override: true
          components: rust-docs
      - uses: nttld/setup-ndk@v1
        id: setup-ndk
        with:
          ndk-version: r22

      - uses: actions/cache@v2
        with:
          path: |
            ~/.cargo/
            target/
          key: docs-${{ hashFiles('**/Cargo.toml') }}

      - uses: actions-rs/cargo@v1
        with:
          command: install
          args: cargo-ndk

      - name: Generate docs
        uses: actions-rs/cargo@v1
        with:
          command: ndk
          args: doc --workspace --no-deps --features=unity2019
        env:
          ANDROID_NDK_HOME: ${{ steps.setup-ndk.outputs.ndk-path }}

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./target/aarch64-linux-android/doc
          publish_branch: docs
