name: Docs
on:
  push:
    branches:
      - master

jobs:
  docs:
    name: Docs
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          profile: minimal
          override: true
          components: rust-docs

      - uses: actions/cache@v2
        with:
          path: |
            ~/.cargo/
            target/
          key: docs-${{ hashFiles('**/Cargo.toml') }}

      - name: Generate docs
        uses: actions-rs/cargo@v1
        with:
          command: doc
          args: --workspace --no-deps --features=unity2019,serde

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./target/doc
          publish_branch: docs
